### ISSUE TITLE
Github page still has `firefox-addon` tag

### ISSUE THREAD

**Issue by ScarletLovell** [aiktb/furiganamaker#258]
### Is your feature request related to a problem? Please describe.

When searching for Furigana add-ons for Firefox on Github this page still shows up in Github search results because of it's tag. Firefox support was disconnected in pull https://github.com/aiktb/FuriganaMaker/pull/142

### Describe the solution you'd like

Remove the tag from the page so future users who are searching for the same Firefox add-on solution do not get confused.

### Validations

- [X] Check if you're on the ***latest Furigana Maker version***.
- [X] Follow our [Code of Conduct](https://www.contributor-covenant.org/version/1/4/code-of-conduct/)
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.
- [ ] I would like to implement this feature via a PR.

**Comment by aiktb** [comment]
Done👍
