### ISSUE TITLE
Add furigana to self-updating websites such as messaging platforms like discord

### ISSUE THREAD

**Issue by ghost** [aiktb/furiganamaker#261]
### Is your feature request related to a problem? Please describe.

The automatic addition of furigana only runs on page initialization. but some messaging platforms add furigana to the page fetching live updates from the server.

### Describe the solution you'd like

Obviously, checking the full page for dynamic updates every few seconds is inefficient, i was hoping to add css selector rules that encompass dynamic area within a website. Such dynamic areas are essentially, individual messages. When furigana is added to one of these blocks, a unique identifier is appended to a HashSet. such a HashSet can be used to maintain the state of furigana for blocks. 

A list of such blocks can be fetched every few seconds (could be 10 seconds, could be 5 seconds, maybe user selectable)

and then, the list is checked throughout the hashset. if an element is not in the hashset, the furigana for such element is added to the page and the element is added to the hashset. 

### Describe alternatives you've considered

instead of a hashset, the element can have an attribute set on it, namely: "furigana_added=true" or something like this. this can prevent the need of a hashset. and most modern messaging platforms that need such a dynamic update feature usually don't leave all the elements in the DOM. they remove and add elements that are near the viewing area. 

Also, this dynamic update feature may be disabled by default and enabled for some websites

### Additional context

There could be other efficient methods to solve this issue that i came up with, most websites usually add or remove from the ends of the said block list. so you could also just check the start or end of the block list and stop iterating from either end once you encounter a furigana added block.

### Validations

- [X] Check if you're on the ***latest Furigana Maker version***.
- [X] Follow our [Code of Conduct](https://www.contributor-covenant.org/version/1/4/code-of-conduct/)
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.
- [ ] I would like to implement this feature via a PR.

**Comment by ghost** [comment]
another thing that came to my mind, i suppose this would have to be asynchronous in nature to prevent user from noticing browser lag

**Comment by ghost** [comment]
so i was going over the source code, and `addFurigana` function seems to be exactly the thing that's needed to perform live updates without adding redundant furigana, I'll try to get it fixed on my end though i must admit to not having any experience with javascript in particular

**Comment by aiktb** [comment]
https://github.com/aiktb/FuriganaMaker/blob/6587cd3aa017e5c0a7a788dfaaab67c897885ad7/entrypoints/autoMark.content.ts#L54

I've watched the DOM changes under body and if you set the selector correctly then the dynamic content should be grabbed correctly.
Can you give me a reproducible example, I'd like to know why this doesn't work correctly in discord.

**Comment by ghost** [comment]
indeed, as i was exploring the codebase, i did come across that.

![image](https://github.com/user-attachments/assets/30003376-0df9-4a21-85fe-1eca182e5b30)

I checked it by passing a `console.log` callback to a new mutationobserver. and very clearly, mutations are observed, but somehow, it doesn't add any furigana to the text.

As a matter of fact, the very now that i am writing this report, the mutations are coming in at a fast rate. 

![image](https://github.com/user-attachments/assets/c22818a0-cd01-4d8d-a8d9-2bd0223dd1ee)

I also have added the above rule

**Comment by aiktb** [comment]
> indeed, as i was exploring the codebase, i did come across that.
> 
> ![image](https://private-user-images.githubusercontent.com/71920621/377032473-30003376-0df9-4a21-85fe-1eca182e5b30.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkwNzk5MzQsIm5iZiI6MTcyOTA3OTYzNCwicGF0aCI6Ii83MTkyMDYyMS8zNzcwMzI0NzMtMzAwMDMzNzYtMGRmOS00YTIxLTg1ZmUtMWVjYTE4MmU1YjMwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE2VDExNTM1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVmZDdiOWVjMGJhOTRjOTkzMzc3M2ZmNTJmZTNiNDNjZGYyNTg2MjhhOTc4MTMwMmNkZTMyMGNkNWU0YmUwYTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.bNAQqdfx74LDLmUxvrpt-H5qRku9_EjvxksoVVaap9E)
> 
> I checked it by passing a `console.log` callback to a new mutationobserver. and very clearly, mutations are observed, but somehow, it doesn't add any furigana to the text.
> 
> As a matter of fact, the very now that i am writing this report, the mutations are coming in at a fast rate.
> 
> ![image](https://private-user-images.githubusercontent.com/71920621/377033608-c22818a0-cd01-4d8d-a8d9-2bd0223dd1ee.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkwNzk5MzQsIm5iZiI6MTcyOTA3OTYzNCwicGF0aCI6Ii83MTkyMDYyMS8zNzcwMzM2MDgtYzIyODE4YTAtY2QwMS00ZDhkLWE4ZDktMmJkMDIyM2RkMWVlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE2VDExNTM1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIxOThiMGZjNWEzN2M0ZDAyMjQyZDMwZmI3NjdmNWQxNDkyNGEyZmVjYmIzZmE3NjNkOGE5M2RiM2Q5ZjkyY2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.xKi1yqJaK6yUZ0ZPaF1BE0oFz7LEk18GytHUgrz_j0s)
> 
> I also have added the above rule

You are using the wrong selector. This was my mistake. The `body` selector was for pre-2.0.0 versions of this extension. After 2.0.0 it was included by default but I forgot to change the text description to remove it.

I will correct the description in the extension later.

For a dynamically updated site you need a more fine-grained selector:
```txt
domain: discord.com
selector: .markup_f8f345
```
![image](https://github.com/user-attachments/assets/74ae4fcf-aff1-4eec-b439-9f91ede2dcb0)
The problem is that the `f8f345` at the end of this selector is suspicious. It seems to be a hash value generated based on the component structure, which may be broken if Discord is updated, but I don't notice that Discord has a more reliable selector.

If this solves your problem, I can close it.

**Comment by ghost** [comment]
mhm, since i know what selector to choose in case it breaks, i suppose it wouldn't be that hard even if discord breaks. Thank you so much! my issue is solved!
