### ISSUE TITLE
Error in furigana creation

### ISSUE THREAD

**Issue by ClotildeHenry** [aiktb/furiganamaker#275]
### Describe the bug

Some Kanji are not read the right way, actually I have an example with a reading that doesn't match at all: 
<img width="905" alt="image" src="https://github.com/user-attachments/assets/d1934ff8-d92d-495a-a2af-fe150a2d8829">
 一人 should be 　ひとり and not いちにち 

It's like the kanji is not recognized.

### Reproduction

selection of a sentence in order to add furigana to it
.... looking at all the kanji to be sure of the reading?

### Expected behavior

each kanji with the appropriate reading (on yomi / kun yomi)

### Browser

Chrome

### Validations

- [X] Check if you're on the ***latest Furigana Maker version***.
- [X] Follow our [Code of Conduct](https://www.contributor-covenant.org/version/1/4/code-of-conduct/)
- [X] Check that there isn't [already an issue](https://github.com/aiktb/FuriganaMaker/issues) that asks for the same feature to avoid creating a duplicate.
- [X] Read the [Contributing Guidelines](https://github.com/aiktb/FuriganaMaker/blob/main/.github/CONTRIBUTING.md).
- [ ] I would like to fix this BUG via a PR.

**Comment by aiktb** [comment]
This is a kuromoji parser bug that I cannot fix, and in fact kuromoji cannot guarantee the correctness of the analysis.

Example:
https://takuyaa.github.io/kuromoji.js/demo/tokenize.html
私は一人で書いたら
![image](https://github.com/user-attachments/assets/7d63cf09-3e1a-4192-8899-76f8c997567f)
