### ISSUE TITLE
Add option for "Always Show" with "Gap"/more space.

### ISSUE THREAD

**Issue by AilurusHush** [aiktb/furiganamaker#74]
### Is your feature request related to a problem? Please describe.

I was testing out all the options to find something comfortable to read - as I have very poor eyesight and dyslexia - I was trying out the other options under the section with "Always Show" and "Hover". 

I like the extra space that the "Hover Gap" option had for the kanji between sentence lines compared to it's 'no gap' counterpart but I would still like to see the furigana above the kanji with a little bit extra space. 

With just the current "Always Show" option, it squishes the characters a little too much together for someone with bad vision/disability. Sometimes the page loads in such a way that the characters even overlap which makes it even more difficult to understand.

(Image showing the option section I'm talking about.)
![image_2024-05-21_045905492](https://github.com/aiktb/FuriganaMaker/assets/35385943/df3ff817-74bb-4d0c-aa4c-ff05e19c3d3e)

(Image of the overlapping kanji and furigana on the front page of JP wiki as example.)
![image_2024-05-21_050331674](https://github.com/aiktb/FuriganaMaker/assets/35385943/4a9e686b-6155-4cba-a9ea-c9a2213e6645)

### Describe the solution you'd like

I'd like it if there could be an added option for an "Always Show" to have more space between the lines to adjust for the added characters. Even if it's only a few pixels worth, just to make it more readable for those with vision disabilities. Maybe called "Always Show with Gap" or something similar.

(Made a little mock-up of what I mean.)
![Screenshot 2024-05-21 051924](https://github.com/aiktb/FuriganaMaker/assets/35385943/8645857e-b673-42bb-ae70-15192138c129)

### Describe alternatives you've considered

The only other option that I can think of is adding the furigana after text in parentheses rather than over the top but that doesn't always work with webpage formats.. I've seen other extension trying something like this and color code the furigana but I never got them to work.

### Additional context

Um, the only other thing that I could think of is that if there is an ability to have/import different fonts from something free like Google Font. Sometimes it makes it easier to read the text than with the default fonts, in terms of the disability issue.

Thank you for your time and consideration!~ orz 

### Validations

- [X] Check if you're on the ***latest Furigana Maker version***.
- [X] Follow our [Code of Conduct](https://www.contributor-covenant.org/version/1/4/code-of-conduct/)
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.
- [ ] I would like to implement this feature via a PR.

**Comment by aiktb** [comment]
![image](https://github.com/aiktb/FuriganaMaker/assets/104723527/a3d31aee-c624-4fd3-a80c-cfb4cb76d6ca)
Hi, regarding this image, can you give me a specific URL?
I would like to investigate why the text overlaps, I have not seen the same on JP Wiki.

**Comment by aiktb** [comment]
The current implementation of this extension does not include any code related to text line-height, and I want to limit the functionality to `ruby` tags as much as possible.

Adding the ability to change line-height is not related to `ruby` tags and could easily break the page layout, which I don't think is a good idea.

And the text overlap you mentioned is a bug, however I can't reproduce it, feel free to reopen this issue if you can provide a way to reproduce it.
