### ISSUE TITLE
Translate / Vocab Feature 

### ISSUE THREAD

**Issue by wr1159** [aiktb/furiganamaker#84]
### Is your feature request related to a problem? Please describe.
Thank you for creating this extension first.

While looking for a furigana extension, I found x6ud and your extension. 
https://github.com/x6ud/auto-furigana-chrome-extension and your extension 

For me as someone with very very basic Japanese knowledge, an ideal furigana extension will be one that 
1. autodetects 
2. vocab feature - for users to translate any words (via word segmentation like with kuromoji) through any manner 
3. display furigana for Kanji and in Hiragana / katakana and not romaji. 

### Describe the solution you'd like

Translation / Vocab feature for words using word segmentisation like auto-furigana to allow users to hover over words and understand the meaning of certain kanji. It would be even better if it is available for all Japanese words and not just kanji.

### Validations

- [X] Check if you're on the ***latest Furigana Maker version***.
- [X] Follow our [Code of Conduct](https://www.contributor-covenant.org/version/1/4/code-of-conduct/)
- [X] Check that there isn't already an issue that asks for the same feature to avoid creating a duplicate.
- [ ] I would like to implement this feature via a PR.

**Comment by aiktb** [comment]
These features are beyond furigana, I wouldn't consider implementing them, and there are too many similar extensions that already do a good job in this regard, such as [Rikaichamp](https://chromewebstore.google.com/detail/pnmaklegiibbioifkmfkgpfnmdehdfan).

**Comment by wr1159** [comment]
Ah that's perfect, thanks!
